/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSkillsRouteRouteImport } from './routes/_dashboard/skills/route'
import { Route as DashboardDashboardRouteRouteImport } from './routes/_dashboard/dashboard/route'
import { Route as DashboardChatChar123SessionIdChar125RouteImport } from './routes/_dashboard/chat/{-$sessionId}'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSkillsRouteRoute = DashboardSkillsRouteRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardRouteRoute = DashboardDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatChar123SessionIdChar125Route =
  DashboardChatChar123SessionIdChar125RouteImport.update({
    id: '/chat/{-$sessionId}',
    path: '/chat/{-$sessionId}',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRouteRoute
  '/skills': typeof DashboardSkillsRouteRoute
  '/chat/{-$sessionId}': typeof DashboardChatChar123SessionIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardDashboardRouteRoute
  '/skills': typeof DashboardSkillsRouteRoute
  '/chat/{-$sessionId}': typeof DashboardChatChar123SessionIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRouteRoute
  '/_dashboard/skills': typeof DashboardSkillsRouteRoute
  '/_dashboard/chat/{-$sessionId}': typeof DashboardChatChar123SessionIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/skills' | '/chat/{-$sessionId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/skills' | '/chat/{-$sessionId}'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/dashboard'
    | '/_dashboard/skills'
    | '/_dashboard/chat/{-$sessionId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/skills': {
      id: '/_dashboard/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof DashboardSkillsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/chat/{-$sessionId}': {
      id: '/_dashboard/chat/{-$sessionId}'
      path: '/chat/{-$sessionId}'
      fullPath: '/chat/{-$sessionId}'
      preLoaderRoute: typeof DashboardChatChar123SessionIdChar125RouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDashboardRouteRoute: typeof DashboardDashboardRouteRoute
  DashboardSkillsRouteRoute: typeof DashboardSkillsRouteRoute
  DashboardChatChar123SessionIdChar125Route: typeof DashboardChatChar123SessionIdChar125Route
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardRouteRoute: DashboardDashboardRouteRoute,
  DashboardSkillsRouteRoute: DashboardSkillsRouteRoute,
  DashboardChatChar123SessionIdChar125Route:
    DashboardChatChar123SessionIdChar125Route,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
